name: Push Docker Image Dev
on:
  push:
    branches:
      - dev # When pushing to dev branch then run this action
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Extract tag name
      run: echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ github.ref_name }}