name: Push Docker Image Master
on:
  push:
    branches:
      - master # When pushing to main branch then run this action
# Env variable
env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_USER}}
  DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_IMAGE_NAME: ${{secrets.REPO_NAME}}

# jobs:
#   push-image-to-docker-hub:  # job name
#     runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
#     steps:
#     - uses: actions/checkout@v2 # first action : checkout source code
#     - name: docker login
#       run: | # log into docker hub account
#         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
#     - name: Build the Docker image # push The image to the docker hub
#       run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ github.ref }}
#     - name: Docker Push
#       run: docker push $DOCKER_USER/$REPO_NAME:${{ github.ref }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref }}
          build-args: |
            APP_VERSION=${{ github.ref }}
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}